import json
import os

import numpy
import matplotlib
import matplotlib.pyplot

import pyopal.objects.field

import harmonic_analysis
import tracking_analysis
import polynomial_fit

"""
Aim is to check/understand:-
* in conventional multipole, does the harmonic analysis 'work'
* in rotated multipole, does the harmonic analysis 'work'
Here, I define 'work' with two studies:
* if we track through a harmonic analysis multipole, do we reproduce the
particle trajectories
* if we look at transfer map generated by a harmonic analysis multipole, do we
reproduce the trajectories
"""

class MetaAnalysis:
    def __init__(self):
        self.simulation = None
        self.harmonics = None
        self.verbose = 0
        self.fit_order = 3
        self.output_dir = f"{os.getcwd()}/plots"
        numpy.set_printoptions(linewidth=200)

    def plot(self, x_data, x_label, y_data, y_label, plot_labels, figname):
        figure = matplotlib.pyplot.figure()
        axes = figure.add_subplot(1, 1, 1)
        for i, x in enumerate(x_data):
            axes.plot(x, y_data[i], label=plot_labels[i])
        axes.set_xlabel(x_label)
        axes.set_ylabel(y_label)
        axes.legend()
        figure.savefig(figname)

    def do_analysis(self):
        tracking_analysis.clear_dir(self.output_dir)
        self.harmonics = harmonic_analysis.HarmonicAnalysis(harmonic_analysis.default_config())
        self.simulation = tracking_analysis.Simulation()
        self.simulation.postprocess = self.postprocess
        self.simulation.delta_vector = numpy.array([100e-3, 100e6, 100e-3, 100e6]) # m, eV
        angle_list = [angle for angle in range(0, 46, 45)]
        rotated_residual_list = []
        quad_residual_list = []
        self.make_simulation_beam()
        rot_tm = []
        quad_tm = []
        for angle in angle_list:
            print("For angle", angle)
            self.simulation.multipoles = [0.0, 1.0, 0.0]
            self.harmonics_file_name = f"{self.output_dir}/harmonics_{angle}_rotated"

            # First we run the analysis with the 1 T/m quad
            self.run_simulation(angle)
            fft_r_rot, fft_phi_rot, fft_l_rot = self.load()
            rot_tm.append(self.get_transfer_map(f"rot_{angle}"))
            rms_residuals = numpy.sum(self.analysis.residuals, axis=0)
            rotated_residual_list.append(rms_residuals)
            print("  rotated residuals:", rms_residuals)

            # Next we run the analysis with the rotated quad
            self.simulation.multipoles = numpy.real(fft_r_rot)[1:4].tolist() # ouput of harmonic analysis
            self.harmonics_file_name = f"{self.output_dir}/harmonics_{angle}_quad"

            self.run_simulation(0)
            fft_r_quad, fft_phi_quad, fft_l_quad = self.load()
            quad_tm.append(self.get_transfer_map(f"quad_{angle}"))
            rms_residuals = numpy.sum(self.analysis.residuals, axis=0)
            quad_residual_list.append(rms_residuals)
            print("  quad residuals:   ", rms_residuals)

        rotated_residual_list = numpy.array(rotated_residual_list)
        quad_residual_list = numpy.array(quad_residual_list)
        label = ["pure quad", "rotated quad"]
        a_list = [angle_list, angle_list]
        a_txt = "angle [deg]"
        self.plot(a_list, a_txt, [quad_residual_list[:,0], rotated_residual_list[:,0]], "x residuals [mm]", label, f"{self.output_dir}/residual_x_vs_angle.png")
        self.plot(a_list, a_txt, [quad_residual_list[:,1], rotated_residual_list[:,1]], "px residuals [MeV/c]", label, f"{self.output_dir}/residual_px_vs_angle.png")
        self.plot(a_list, a_txt, [quad_residual_list[:,2], rotated_residual_list[:,2]], "y residuals [mm]", label, f"{self.output_dir}/residual_y_vs_angle.png")
        self.plot(a_list, a_txt, [quad_residual_list[:,3], rotated_residual_list[:,3]], "py residuals [MeV/c]", label, f"{self.output_dir}/residual_py_vs_angle.png")

        self.plot_tm(quad_tm, rot_tm, angle_list)

    def get_indices(self, order):
        pfit = polynomial_fit.PolynomialFit()
        pfit.polynomial_order = order
        pfit.dimension = 4
        indices = pfit.make_polynomial_indices()
        return indices

    def get_submatrix(self, tm, order):
        indices = self.get_indices(order)
        r0 = len([i for i in indices if len(i) < order])
        submatrix = tm[:,r0:]
        return submatrix

    def plot_tm(self, quad_tm, rot_tm, angle_list):

        for plot_order in range(self.fit_order+1):
            subindices = [i for i in self.get_indices(plot_order) if len(i) == plot_order]
            quad_submatrix = [self.get_submatrix(tm, plot_order) for tm in quad_tm]
            rot_submatrix = [self.get_submatrix(tm, plot_order) for tm in rot_tm]

            figure = matplotlib.pyplot.figure()
            axes = figure.add_subplot(1, 1, 1)
            axes.set_xlabel("angle [deg]")
            axes.set_ylabel("TM term [AU]")

            for iin, index in enumerate(subindices):
                for iout in range(4):
                    quad_sm_data = [sm[iout, iin] for sm in quad_submatrix]
                    if [iout] == index:
                        quad_sm_data = [q-1 for q in quad_sm_data]

                    axes.plot(angle_list, quad_sm_data, label=f"{iout}; {str(index)}")
            #axes.legend()
            axes.set_title(f"TM terms order {plot_order} for harmonic analysis quad")
            figure.savefig(f"{self.output_dir}/tm_terms_quad_{plot_order}.png")

            figure = matplotlib.pyplot.figure()
            axes = figure.add_subplot(1, 1, 1)
            axes.set_xlabel("angle [deg]")
            axes.set_ylabel("TM term [AU]")

            for iin, index in enumerate(subindices):
                for iout in range(4):
                    rot_sm_data = [sm[iout, iin] for sm in rot_submatrix]
                    if [iout] == index:
                        rot_sm_data = [q-1 for q in rot_sm_data]

                    axes.plot(angle_list, rot_sm_data, label=f"{iout}; {str(index)}")
            max_index = numpy.argmin(rot_submatrix[-1])
            max_index = numpy.unravel_index(max_index, rot_submatrix[-1].shape)
            print(f"Min TM term for plot order {plot_order}", max_index, " i.e. ", max_index[0], subindices[max_index[1]], "value", rot_submatrix[-1][max_index])
            print("For indices", subindices)
            #axes.legend()
            axes.set_title(f"TM terms order {plot_order} for rotated quad")
            figure.savefig(f"{self.output_dir}/tm_terms_rot_{plot_order}.png")


    def postprocess(self):
        self.plot_field() # plot a field map to check wtf is going on
        self.do_harmonics() # do the harmonic analysis; ffts are now in self.harmonics

    def plot_field(self):
        x_list, y_list, b_list = [], [], []
        r0 = self.simulation.r0
        for xi in range(-100, 101):
            for yi in range(-100, 101):
                point = (r0+xi*2e-2, yi*2e-2, 0.0, 0.0)
                x_list.append(point[0])
                y_list.append(point[1])
                field = pyopal.objects.field.get_field_value(*point)
                bfield = (field[1]**2+field[2]**2+field[3]**2)**0.5
                b_list.append(bfield)
        fig = matplotlib.pyplot.figure()
        fig.add_subplot(1,1,1).hist2d(x_list, y_list, weights=b_list, bins=[101, 101])
        fig.savefig(f"{self.output_dir}/bfield_{self.simulation.angle}.png")

    def do_harmonics(self):
        #HarmonicsAnalysis.trajectory_columns = ["id", "x", "xp", "y", "yp", "z", "zp"]
        self.harmonics.verbose = self.verbose
        step = self.simulation.angle
        r0 = self.simulation.r0
        psv = {"step":step, "id":1, "x":r0, "y":0.0, "z":0.0, "xp":0.0, "yp":1.0, "zp":0.0}
        fft_r, fft_phi, fft_l = self.harmonics.analyse_one_step(psv, True)
        self.save(fft_r, fft_phi, fft_l)

    def save(self, fft_r, fft_phi, fft_l):
        with open(self.harmonics_file_name, "w") as fout:
            serialisation = {}
            serialisation["fft_r_re"] = numpy.real(fft_r).tolist()
            serialisation["fft_r_im"] = numpy.imag(fft_r).tolist()
            serialisation["fft_phi_re"] = numpy.real(fft_phi).tolist()
            serialisation["fft_phi_im"] = numpy.imag(fft_phi).tolist()
            serialisation["fft_l_re"] = numpy.real(fft_l).tolist()
            serialisation["fft_l_im"] = numpy.imag(fft_l).tolist()
            fout.write(json.dumps(serialisation))

    def load(self):
        with open(self.harmonics_file_name) as fin:
            serialisation = json.loads(fin.read())
            fft_r = numpy.array(serialisation["fft_r_re"])+ \
                    numpy.array(serialisation["fft_r_im"])*1j
            fft_phi = numpy.array(serialisation["fft_phi_re"])+ \
                    numpy.array(serialisation["fft_phi_im"])*1j
            fft_l = numpy.array(serialisation["fft_l_re"])+ \
                    numpy.array(serialisation["fft_l_im"])*1j
            return fft_r, fft_phi, fft_l

    def make_simulation_beam(self):
        self.simulation.n_particles = 100
        self.simulation.particle_algorithm = "scatter"
        self.simulation.setup()

    def run_simulation(self, angle):
        self.simulation.angle = angle
        self.simulation.verbose = self.verbose
        if self.verbose > 0:
            print(f"Simulation running in {self.simulation.tmp_dir}")
        backend = matplotlib.get_backend()
        # switch to batch backend;
        matplotlib.use("agg")
        self.simulation.execute_fork()
        # switch back to interactive mode
        matplotlib.use(backend)

    def get_transfer_map(self, style):
        self.analysis = tracking_analysis.TrackingAnalysis()
        self.analysis.algorithm = "linear_least_squares" #"differential_evolution"
        self.analysis.fit_order = self.fit_order
        self.analysis.verbose = self.verbose
        self.analysis.delta_vector = self.simulation.delta_vector
        self.analysis.do_plots(f"{self.output_dir}/residuals_{style}_o_{self.analysis.fit_order}.png")
        return self.analysis.polynomial.get_coefficients()

def main():
    analysis = MetaAnalysis()
    analysis.do_analysis()

if __name__ == "__main__":
    main()
    matplotlib.pyplot.show(block=False)
    input("Press <enter> to finish")

